/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ProductApiService := openapi.NewProductApiService()
	ProductApiController := openapi.NewProductApiController(ProductApiService)

	router := openapi.NewRouter(ProductApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
