/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// ProductApiRouter defines the required methods for binding the api requests to a responses for the ProductApi
// The ProductApiRouter implementation should parse necessary information from the http request,
// pass the data to a ProductApiServicer to perform the required actions, then write the service results to the http response.
type ProductApiRouter interface { 
	DeleteProductById(http.ResponseWriter, *http.Request)
	GetProductById(http.ResponseWriter, *http.Request)
	GetProducts(http.ResponseWriter, *http.Request)
}


// ProductApiServicer defines the api actions for the ProductApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ProductApiServicer interface { 
	DeleteProductById(context.Context, int64) (ImplResponse, error)
	GetProductById(context.Context, int64) (ImplResponse, error)
	GetProducts(context.Context, int32, string) (ImplResponse, error)
}
