/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ModelError struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}

// AssertModelErrorRequired checks if the required fields are not zero-ed
func AssertModelErrorRequired(obj ModelError) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseModelErrorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ModelError (e.g. [][]ModelError), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModelErrorRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModelError, ok := obj.(ModelError)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModelErrorRequired(aModelError)
	})
}
