/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Page struct {

	NextPageToken string `json:"nextPageToken,omitempty"`
}

// AssertPageRequired checks if the required fields are not zero-ed
func AssertPageRequired(obj Page) error {
	return nil
}

// AssertRecursePageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Page (e.g. [][]Page), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPage, ok := obj.(Page)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPageRequired(aPage)
	})
}
