/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProductsAllOf struct {

	Items []Product `json:"items,omitempty"`
}

// AssertProductsAllOfRequired checks if the required fields are not zero-ed
func AssertProductsAllOfRequired(obj ProductsAllOf) error {
	for _, el := range obj.Items {
		if err := AssertProductRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseProductsAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ProductsAllOf (e.g. [][]ProductsAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProductsAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProductsAllOf, ok := obj.(ProductsAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProductsAllOfRequired(aProductsAllOf)
	})
}
