/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Products struct {

	NextPageToken string `json:"nextPageToken,omitempty"`

	Items []Product `json:"items,omitempty"`
}

// AssertProductsRequired checks if the required fields are not zero-ed
func AssertProductsRequired(obj Products) error {
	for _, el := range obj.Items {
		if err := AssertProductRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseProductsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Products (e.g. [][]Products), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProductsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProducts, ok := obj.(Products)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProductsRequired(aProducts)
	})
}
