product:
  type: object
  required:
    - id
    - name
    - localizedName
    - imageUrl
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    localizedName:
      type: string
    imageUrl:
      type: string
products:
  allOf:
    - $ref: "./page.yaml#/page"
    - type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/product"
