/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteProductById - Cancel a specified product
func DeleteProductById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetProductById - Get a specified product
func GetProductById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetProducts - Get all products
func GetProducts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
