/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Product struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	LocalizedName string `json:"localizedName"`

	ImageUrl string `json:"imageUrl"`
}
