/*
 * EC
 *
 * EC API
 *
 * API version: 2023.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProductsAllOf struct {

	Items []Product `json:"items,omitempty"`
}
